### ISSUE TITLE
Fleek deploy failed without branch specified

### ISSUE THREAD

**Issue by zenfinity** [MicrogenSite/microgen#156]
I just did first deploy on fleek (lol) and followed the `SETUP.md` instructions, and it failed until `NEXT_PUBLIC_TINA_BRANCH` was specified as another env variable in addition to `NEXT_PUBLIC_TINA_CLIENT_ID` and `TINA_TOKEN`. I set it as `main`. Not sure if this is a new thing, but maybe can just add a line in the doc.

**Comment by tbenbow** [comment]
Thanks for this call out @zenfinity - I'll update the docs as you suggest.

**Comment by tbenbow** [comment]
This has been updated in the docs with release v1.9. Thanks again for pointing this out.
